# Generated by Django 5.0.1 on 2024-01-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('AD', 'Audio'), ('MC', 'Microphone')], max_length=10)),
            ],
        ),
    ]
